name: smart_parking
description: parking reservation app

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.8.2+3
  qr_flutter: ^1.1.5
  http: ^0.12.0
  firebase_storage: ^1.0.4
  random_string: ^0.0.2
  cached_network_image: ^0.5.1
  transparent_image: ^0.1.0
  image_picker: ^0.4.10
  google_maps_flutter: ^0.4.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
      - assets/

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

